### ISSUE TITLE
Implement model default value

### ISSUE THREAD

**Issue by ncaq** [happenslol/tree-sitter-typespec#11]
[Implement values grammar · Issue #2 · happenslol/tree-sitter-typespec](https://github.com/happenslol/tree-sitter-typespec/issues/2)

I thought it was the same as the issue above, but this was a different story.

[Models | TypeSpec](https://typespec.io/docs/language-basics/models/)

``` tsp
model Dog {
  address?: string = "wild";
}
```

**Comment by happenslol** [comment]
Closed by #12
