### ISSUE TITLE
Add LICENSE.txt

### ISSUE THREAD

**Issue by heaths** [happenslol/tree-sitter-typespec#5]
Could you add a license to this repo so it can be included in helix? helix-editor/helix#11412

I recommend something permissive that we could potentially build and include on this in the future if VSCode ends up supporting tree-sitter. The TypeSpec repo uses the MIT license: https://github.com/microsoft/typespec/blob/main/LICENSE

**Comment by happenslol** [comment]
Ah, that's an oversight, it was always meant to be MIT. License file has been added!
