### ISSUE TITLE
highlighting not working

### ISSUE THREAD

**Issue by Quesj** [happenslol/tree-sitter-typespec#6]
Hello! 

Nice work on the extension for TypeSpec! Been looking everywhere for a while. Your package installs correctly but I do not get any syntax highlighting.  

I've tried installing it via: 

```lua
require("nvim-treesitter.configs").setup({
	ensure_installed = { "lua", "vim", "vimdoc", "javascript", "typescript", "typespec" },

	sync_install = false,

	auto_install = true,

	highlight = {
		enable = true,
	},
})
```

**Comment by happenslol** [comment]
Not sure if this is the correct place for this, since this package is not vim-specific.

I do have one idea though: are you on the newest vim/neovim version? The editor needs to correctly recognize .tsp files as typespec for tree-sitter to work. You can try running `:set ft=typespec` to test this.

**Comment by Quesj** [comment]
You were right, I had to install a new version of nvim! Thanks again!
